(() => {
const oldPersist=persist, oldRender=render, oldOpenProject=openProject, oldReadProject=readProject, oldShowView=showView, oldSyncProject=syncProject, oldLoadFromDb=loadFromDb;
const ensureGov=p=>{p.governance ||= {approvalStage:'Draft',decisionOwner:'',decisionDate:'',targetDate:'',milestones:[],dependencies:[],risks:[]}; return p};
projects.forEach(ensureGov); oldPersist();
persist=()=>{projects.forEach(ensureGov);oldPersist()};
function optionProjects(selected=''){return projects.filter(p=>p.id!==editingId).map(p=>`<option value="${p.id}" ${selected===p.id?'selected':''}>${escapeHtml(p.name)}</option>`).join('')}
function milestoneHtml(m={name:'',date:'',status:'Planned'}){return `<div class="milestone"><input class="milestoneName" placeholder="Milestone name" value="${escapeHtml(m.name||'')}"><input class="milestoneDate" type="month" value="${m.date||''}"><button type="button" class="icon removeGovRow">×</button></div>`}
function dependencyHtml(d={projectId:'',type:'Finish-to-Start'}){return `<div class="dependency"><select class="dependencyProject"><option value="">Choose predecessor</option>${optionProjects(d.projectId)}</select><select class="dependencyType"><option ${d.type==='Finish-to-Start'?'selected':''}>Finish-to-Start</option><option ${d.type==='Start-to-Start'?'selected':''}>Start-to-Start</option></select><button type="button" class="icon removeGovRow">×</button></div>`}
function riskHtml(r={description:'',severity:'Medium',mitigation:'',status:'Open'}){return `<div class="riskInput"><input class="riskDescription" placeholder="Risk description" value="${escapeHtml(r.description||'')}"><select class="riskSeverity"><option>Low</option><option ${r.severity==='Medium'?'selected':''}>Medium</option><option ${r.severity==='High'?'selected':''}>High</option><option ${r.severity==='Critical'?'selected':''}>Critical</option></select><input class="riskMitigation" placeholder="Mitigation or owner" value="${escapeHtml(r.mitigation||'')}"><button type="button" class="icon removeGovRow">×</button></div>`}
function bindGovRows(){$$('.removeGovRow').forEach(b=>b.onclick=()=>b.parentElement.remove())}
function renderGovEditor(g){$('#approvalStage').value=g.approvalStage||'Draft';$('#decisionOwner').value=g.decisionOwner||'';$('#decisionDate').value=g.decisionDate||'';$('#targetDate').value=g.targetDate||'';$('#milestoneRows').innerHTML=(g.milestones||[]).map(milestoneHtml).join('');$('#dependencyRows').innerHTML=(g.dependencies||[]).map(dependencyHtml).join('');$('#riskRows').innerHTML=(g.risks||[]).map(riskHtml).join('');bindGovRows()}
function readGov(){return {approvalStage:$('#approvalStage').value,decisionOwner:$('#decisionOwner').value.trim(),decisionDate:$('#decisionDate').value,targetDate:$('#targetDate').value,milestones:$$('.milestone').map(x=>({name:x.querySelector('.milestoneName').value.trim(),date:x.querySelector('.milestoneDate').value,status:'Planned'})).filter(x=>x.name),dependencies:$$('.dependency').map(x=>({projectId:x.querySelector('.dependencyProject').value,type:x.querySelector('.dependencyType').value})).filter(x=>x.projectId),risks:$$('.riskInput').map(x=>({description:x.querySelector('.riskDescription').value.trim(),severity:x.querySelector('.riskSeverity').value,mitigation:x.querySelector('.riskMitigation').value.trim(),status:'Open'})).filter(x=>x.description)}}
openProject=id=>{oldOpenProject(id);const p=ensureGov(id?projects.find(x=>x.id===id):{governance:{}});renderGovEditor(p.governance)};
readProject=()=>{const p=oldReadProject();p.governance=readGov();return p};
function dependencyBlocked(p){return (p.governance?.dependencies||[]).some(d=>{const pred=projects.find(x=>x.id===d.projectId);return pred && pred.status!=='Completed'})}
function renderRoadmap(){const sel=$('#roadmapYear');if(!sel)return;const years=[...new Set(projects.map(p=>(p.startDate||'2027').slice(0,4)))].sort();if(!sel.options.length){sel.innerHTML=years.map(y=>`<option>${y}</option>`).join('')||'<option>2027</option>';sel.value=years[0]||'2027'}const year=Number(sel.value);const monthNames=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];let html=`<div class="roadmapHeader"><div>Project</div>${monthNames.map(m=>`<div>${m}</div>`).join('')}</div>`;projects.filter(p=>(p.startDate||'').startsWith(String(year))).sort((a,b)=>(a.startDate||'').localeCompare(b.startDate||'')).forEach(p=>{const c=calculate(p),start=Number((p.startDate||`${year}-01`).slice(5,7))-1,blocked=dependencyBlocked(p);const cells=Array.from({length:12},(_,m)=>{if(m<start||m>=start+c.months)return '<div class="roadCell"></div>';const label=m===start?(blocked?'Blocked':c.months+' mo.'):' ';return `<div class="roadCell"><div class="roadBar ${blocked?'blocked':p.governance.approvalStage.includes('Review')?'review':''}">${label}</div></div>`}).join('');html+=`<div class="roadmapRow"><div class="roadmapName"><b>${escapeHtml(p.name)}</b><small>${escapeHtml(p.division)} · ${escapeHtml(p.governance.approvalStage)}</small>${blocked?'<span class="blockedNote">Waiting on dependency</span>':''}</div>${cells}</div>`});$('#roadmapGrid').innerHTML=html||'<div class="empty">No scheduled projects.</div>'}
function approvalCard(p){const c=calculate(p);return `<div class="governanceCard"><header><b>${escapeHtml(p.name)}</b><span class="pill">${escapeHtml(p.governance.approvalStage)}</span></header><small>${escapeHtml(p.division)} · ${money(c.totalSpend)} · Priority ${c.priority.toFixed(0)}</small><small>Owner: ${escapeHtml(p.governance.decisionOwner||'Unassigned')}</small><div class="miniActions"><button data-approve="${p.id}" class="primary">Approve</button><button data-review="${p.id}">Advance Review</button></div></div>`}
function renderGovernance(){if(!$('#governanceKpis'))return;const pending=projects.filter(p=>!['Approved','Rejected'].includes(p.governance.approvalStage)),high=projects.flatMap(p=>(p.governance.risks||[]).filter(r=>['High','Critical'].includes(r.severity))),blocked=projects.filter(dependencyBlocked),approved=projects.filter(p=>p.governance.approvalStage==='Approved');$('#governanceKpis').innerHTML=[['Pending Approval',pending.length],['Approved',approved.length],['High/Critical Risks',high.length],['Dependency Blocked',blocked.length]].map(x=>`<div class="kpi"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');$('#approvalQueue').innerHTML=pending.map(approvalCard).join('')||'<div class="empty">No projects awaiting approval.</div>';$('#riskRegister').innerHTML=projects.flatMap(p=>(p.governance.risks||[]).filter(r=>r.status!=='Closed').map(r=>`<div class="riskCard"><header><b>${escapeHtml(p.name)}</b><span class="severity ${r.severity.toLowerCase()}">${r.severity}</span></header><span>${escapeHtml(r.description)}</span><small>${escapeHtml(r.mitigation||'No mitigation entered')}</small></div>`)).join('')||'<div class="empty">No open risks.</div>';$$('[data-approve]').forEach(b=>b.onclick=()=>{const p=projects.find(x=>x.id===b.dataset.approve);p.governance.approvalStage='Approved';p.status='Approved';persist();render()});$$('[data-review]').forEach(b=>b.onclick=()=>{const p=projects.find(x=>x.id===b.dataset.review),stages=['Draft','Department Review','Finance Review','Executive Review','Approved'];const i=stages.indexOf(p.governance.approvalStage);p.governance.approvalStage=stages[Math.min(stages.length-1,Math.max(0,i)+1)];persist();render()})}
render=()=>{oldRender();renderRoadmap();renderGovernance()};
showView=v=>{oldShowView(v);const labels={roadmap:['Initiative Roadmap','Review calculated timing, milestones, and predecessor constraints.'],governance:['Project Governance','Manage approvals, dependencies, milestones, and portfolio risks.']};if(labels[v]){$('#pageTitle').textContent=labels[v][0];$('#pageSubtitle').textContent=labels[v][1];$('#newProject').classList.remove('hidden')}};
syncProject=async p=>{await oldSyncProject(p);if(!db)return;const g=p.governance||{};await Promise.all([db.from('project_governance').upsert({project_id:p.id,approval_stage:g.approvalStage,decision_owner:g.decisionOwner||null,decision_date:g.decisionDate||null,target_date:g.targetDate?`${g.targetDate}-01`:null}),db.from('project_milestones').delete().eq('project_id',p.id),db.from('project_dependencies').delete().eq('project_id',p.id),db.from('project_risks').delete().eq('project_id',p.id)]);if(g.milestones?.length)await db.from('project_milestones').insert(g.milestones.map(x=>({project_id:p.id,name:x.name,due_date:x.date?`${x.date}-01`:null,status:x.status})));if(g.dependencies?.length)await db.from('project_dependencies').insert(g.dependencies.map(x=>({project_id:p.id,depends_on_project_id:x.projectId,dependency_type:x.type})));if(g.risks?.length)await db.from('project_risks').insert(g.risks.map(x=>({project_id:p.id,description:x.description,severity:x.severity,mitigation:x.mitigation,status:x.status}))) };
$('#addMilestone').onclick=()=>{$('#milestoneRows').insertAdjacentHTML('beforeend',milestoneHtml());bindGovRows()};$('#addDependency').onclick=()=>{$('#dependencyRows').insertAdjacentHTML('beforeend',dependencyHtml());bindGovRows()};$('#addRisk').onclick=()=>{$('#riskRows').insertAdjacentHTML('beforeend',riskHtml());bindGovRows()};$('#roadmapYear').onchange=renderRoadmap;
render();
})();
